name: Minimum Business Requirement
description: Create a New MBI
title: "[MBI]: "
labels: [MBI,need triaging]
body:
  - type: markdown
    attributes:
      value: |
        Before creating MBI , please search for the behaviour in the existing MBIs. 
        
        ---
        
        Thank you for taking the time in creating a new MBI.
  - type: dropdown
    id: initId
    attributes:
      label: Parent Initiative ID
      description: "MBI need to be part of Initiative? Please provide the the parent ID."
      options:
        - 10052 Global Marine Order Proecessing Automation 
        - 10054 Ethena Performance Enahancement
        - 10058 Food Servicing Industry Automation (Exploration) 
    validations:
      required: true  
  - type: dropdown
    id: location
    attributes:
      label: Targeted Region
      description: Where is the project located?
      options:
        - Global
        - USA
        - EU
        - Somewhere else (please specify in the description!)
    validations:
      required: true
  - type: textarea
    id: mbi-description
    attributes:
      label: MBI description
      description: What happened and what did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: valprop
    attributes:
      label: Value Proposition
      description: What are the Anticipated benefit of this MBI ?
